// Generates app/themes.css from lib/themes.data.mjs. Run with `pnpm themes`; the unit test
// fails when the committed file drifts from the registry.
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEFAULT_THEME, THEMES } from '../lib/themes.data.mjs'

function block(selector, theme) {
  const lines = Object.entries(theme.tokens).map(([k, v]) => `  --${k}: ${v.toLowerCase()};`)
  // The void is the dark half of the world, whichever half that is, and void-ink is what is
  // legible on it. P/03 goes inside it, so it has to read as a hole in every theme and not as a
  // bright patch in the two that are already dark.
  const dark = theme.scheme === 'dark'
  lines.push(`  --void: ${(dark ? theme.tokens.canvas : theme.tokens.ink).toLowerCase()};`)
  lines.push(`  --void-ink: ${(dark ? theme.tokens.ink : theme.tokens.canvas).toLowerCase()};`)
  lines.push(`  color-scheme: ${theme.scheme};`)
  return `${selector} {\n${lines.join('\n')}\n}\n`
}

export function render() {
  const def = THEMES.find((t) => t.name === DEFAULT_THEME)
  const out = [
    '/* Generated by scripts/gen-themes.mjs from lib/themes.data.mjs. Do not edit by hand. */',
    `/* Default (no data-theme, no JS): ${def.name}. */`,
    block(':root', def),
    ...THEMES.map((t) => block(`[data-theme='${t.name}']`, t)),
  ]
  return out.join('\n')
}

const here = fileURLToPath(import.meta.url)
if (process.argv[1] && path.resolve(process.argv[1]) === here) {
  const target = path.resolve(path.dirname(here), '../app/themes.css')
  writeFileSync(target, render())
  console.log(`wrote ${path.relative(process.cwd(), target)} (${THEMES.length} themes)`)
}
