// Generates app/themes.css from lib/themes.data.mjs. Run with `pnpm themes`; the unit test
// fails when the committed file drifts from the registry.
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEFAULT_THEME, THEMES } from '../lib/themes.data.mjs'

function block(selector, theme) {
  const lines = Object.entries(theme.tokens).map(([k, v]) => `  --${k}: ${v.toLowerCase()};`)
  lines.push(`  color-scheme: ${theme.scheme};`)
  return `${selector} {\n${lines.join('\n')}\n}\n`
}

export function render() {
  const def = THEMES.find((t) => t.name === DEFAULT_THEME)
  const out = [
    '/* Generated by scripts/gen-themes.mjs from lib/themes.data.mjs. Do not edit by hand. */',
    `/* Default (no data-theme, no JS): ${def.name}. */`,
    block(':root', def),
    ...THEMES.map((t) => block(`[data-theme='${t.name}']`, t)),
  ]
  return out.join('\n')
}

const here = fileURLToPath(import.meta.url)
if (process.argv[1] && path.resolve(process.argv[1]) === here) {
  const target = path.resolve(path.dirname(here), '../app/themes.css')
  writeFileSync(target, render())
  console.log(`wrote ${path.relative(process.cwd(), target)} (${THEMES.length} themes)`)
}
